version: "3.9"  # optional since v1.27.0
services:

  match:
    build: ./match-api
    volumes:
      - ./match-api/src:/match-api/src
    ports:
      - "3100:3100"
    depends_on:
      - user
    command: npm run debug-docker
  user:
    build: ./users-api
    volumes:
      - ./users-api/src:/users-api/src
    ports:
      - "3000:3000"
    command: npm run debug-docker
  proxy:
    image: nginx
    volumes:
      - ./proxy:/etc/nginx:ro
    ports:
      - "80:80"
    depends_on:
      - users
      - match